/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/goalsService`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../navigation/NutStackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/CreateNutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EditNutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EditExScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/goalsService`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../navigation/NutStackNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/CreateNutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/EditNutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/EditExScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/goalsService${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/../navigation/NutStackNavigator${`?${string}` | `#${string}` | ''}` | `/../screens/CreateNutScreen${`?${string}` | `#${string}` | ''}` | `/../screens/EditNutScreen${`?${string}` | `#${string}` | ''}` | `/../screens/EditExScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/goalsService`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../navigation/NutStackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/CreateNutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EditNutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EditExScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
