/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/goalsService`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/nutService`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/userService`; params?: Router.UnknownInputParams; } | { pathname: `/../navigation/HomeStackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/userService.test`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/goalsService`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/nutService`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/userService`; params?: Router.UnknownOutputParams; } | { pathname: `/../navigation/HomeStackNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/userService.test`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/goalsService${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/nutService${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/userService${`?${string}` | `#${string}` | ''}` | `/../navigation/HomeStackNavigator${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/__tests__/userService.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/goalsService`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/nutService`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/userService`; params?: Router.UnknownInputParams; } | { pathname: `/../navigation/HomeStackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/userService.test`; params?: Router.UnknownInputParams; };
    }
  }
}
